### ISSUE TITLE
Route method always GET|HEAD

### ISSUE THREAD

**Issue by mstaack** [jakubkratina/lumen-dingo-route-list#1]
It looks like on latest lumen and dingo the command returns always `GET | HEAD`

If i register a route:

```
$api->post('users', ['uses' => 'App\Http\Controllers\UserController@index', 'as' => 'user.index']);
```

It should show up as POST in method column but it doesnt

**Comment by jakubkratina** [comment]
Yeah, its bug in the Dingo, I'll make a pull request. Thank you for your issue.

**Comment by jakubkratina** [comment]
We will see: https://github.com/dingo/api/pull/1057
